$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1476953255966.09),
  "isCanvasEnabled":false,
  "variables":["zjBianliang"],
  "page":{
    "packageId":"c4430af80a13445785461b54dcd91e9d",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7135079104fb499c812fb4a25818ee61",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"9c444d98c8ad4badba0495e43c470eed"},
{
          "id":"a6fc58137f86469b907aa4df06ae0da6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":577,
              "y":169},
            "size":{
              "width":73,
              "height":1},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5085303de9a24c2888bec557297123db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":577,
                  "y":169},
                "size":{
                  "width":73,
                  "height":1},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u29.png"}},
{
          "id":"7e264161e7364a0c88a68ed3e7e12f6f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":650,
              "y":169},
            "size":{
              "width":247,
              "height":1},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"318578aaa4da48918bc7d0f99960e971",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":650,
                  "y":169},
                "size":{
                  "width":247,
                  "height":1},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u31.png"}},
{
          "id":"770e099b357e4d358fe7efb234dfb8c5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":540,
              "y":170},
            "size":{
              "width":19,
              "height":1},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86135c74df8341e0b33b7125fa7e32cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":540,
                  "y":170},
                "size":{
                  "width":19,
                  "height":1},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u33.png"}},
{
          "id":"5a09cf7129f94a7cb771536aa2a39cf2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":559,
              "y":170},
            "size":{
              "width":228,
              "height":1},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e94ada81e5a4f0a8c738c876123f1bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":559,
                  "y":170},
                "size":{
                  "width":228,
                  "height":1},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u35.png"}},
{
          "id":"4177228e8e46435fab3890c8f7cb9653",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":559,
              "y":171},
            "size":{
              "width":163,
              "height":1},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a515c45a48d40dcb1460ee97fcef62e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":559,
                  "y":171},
                "size":{
                  "width":163,
                  "height":1},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u37.png"}},
{
          "id":"07d3b43575f64d3094ceb1b0f5410d03",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":722,
              "y":171},
            "size":{
              "width":65,
              "height":1},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8424618f1b4e48e29dd87dba53228938",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":722,
                  "y":171},
                "size":{
                  "width":65,
                  "height":1},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u39.png"}},
{
          "id":"617768a282de493b8f0b74fe599a9b31",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":484,
              "y":183},
            "size":{
              "width":415,
              "height":708},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a203781d804f4273a8b1143a7fa127ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":484,
                  "y":183},
                "size":{
                  "width":415,
                  "height":708},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u41.png"}},
{
          "id":"fcf3e1d3e4e34b6f972797dbb5615124",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5E5E5E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":544,
              "y":836},
            "size":{
              "width":116,
              "height":54},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2df206ed0b864b1a9ebbd33cbef26a35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5E5E5E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":544,
                  "y":836},
                "size":{
                  "width":116,
                  "height":54},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u43.png"}},
{
          "id":"1a878da1c73c4e1c881430be15c2362c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5E5E5E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":662,
              "y":836},
            "size":{
              "width":116,
              "height":54},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e701f125deb449c39ef9eef2ea3430d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5E5E5E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":662,
                  "y":836},
                "size":{
                  "width":116,
                  "height":54},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 引导页",
                      "target":{
                        "targetType":"page",
                        "url":"引导页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u43.png"}},
{
          "id":"34769ef1f5134dfe8c027f69c3975c77",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5E5E5E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":781,
              "y":836},
            "size":{
              "width":116,
              "height":54},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a21455b3b46c4c3294da67a98dddeb09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5E5E5E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":781,
                  "y":836},
                "size":{
                  "width":116,
                  "height":54},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u43.png"}}]}},
  "masters":{
    "9c444d98c8ad4badba0495e43c470eed":{
      "packageId":"9c444d98c8ad4badba0495e43c470eed",
      "type":"Axure:Master",
      "name":"6Plus",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
        "onLoad":{
          "description":"OnLoad",
          "cases":[{
              "description":"Case 1",
              "isNewIfGroup":false,
              "actions":[{
                  "action":"setPanelState",
                  "description":"设置 wifiTop to Next wrap repeat every 2000 ms",
                  "panelsToStates":[{
                      "panelPath":["4baa3849a6934260a45030ac57567a6b"],
                      "stateInfo":{
                        "setStateType":"next",
                        "stateNumber":1,
                        "stateValue":{
                          "exprType":"stringLiteral",
                          "value":"1",
                          "stos":[]},
                        "loop":true,
                        "showWhenSet":false,
                        "repeat":2000,
                        "options":{
                          "compress":false}}}]}]}]}},
      "diagram":{
        "objects":[{
            "id":"71e7261c93754d60bfca3c333757e5d4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":455,
                "y":48},
              "size":{
                "width":473,
                "height":954}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"204649a0a9dc47eb89abd6a14d4dee21",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":455,
                    "y":48},
                  "size":{
                    "width":473,
                    "height":954}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u1.png"}},
{
            "id":"d700736c21484b85ad0944f69ac1e7c3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"solid",
                "color":0xFFEEEEEE},
              "location":{
                "x":484,
                "y":155},
              "size":{
                "width":414,
                "height":736},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cc0c88680ba74275bccb21c8d33ea1ba",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFEEEEEE},
                  "location":{
                    "x":484,
                    "y":155},
                  "size":{
                    "width":414,
                    "height":736},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u3.png"}},
{
            "id":"43b2f4d51be64871b568dfcaa3b2336b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":484,
                "y":837},
              "size":{
                "width":415,
                "height":55},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4646b51c0e674d0db291b14d326f31f8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":484,
                    "y":837},
                  "size":{
                    "width":415,
                    "height":55},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u5.png"}},
{
            "id":"febbf591085046688dacfd42834355b7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"solid",
                "color":0xFF000000},
              "location":{
                "x":484,
                "y":154},
              "size":{
                "width":414,
                "height":28},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da4d2efdcb5140b0823431cbc21f605a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF000000},
                  "location":{
                    "x":484,
                    "y":154},
                  "size":{
                    "width":414,
                    "height":28},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"4e9f28d7f8d24f1c8ac5423a22772cd8",
            "label":"timeTop",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"12px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":696,
                "y":161},
              "size":{
                "width":32,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ff218708f6f24d8e95f20e0c6e80781e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"12px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":696,
                    "y":161},
                  "size":{
                    "width":32,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c26b88e180ca4cf385fb5f6c3f6b8240",
            "label":"AM/PM",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":655,
                "y":161},
              "size":{
                "width":50,
                "height":14}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"f0258397969f45caa06b7077c82a5b92",
                "label":"AM",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"a0cc51770c704b1da4e8db2045b241ad",
                    "label":"AM/PM",
                    "parentDynamicPanel":"c26b88e180ca4cf385fb5f6c3f6b8240",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "fontSize":"12px",
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "size":{
                        "width":50,
                        "height":14}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9c4ef89875c2435db7b2e1110e920849",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"c26b88e180ca4cf385fb5f6c3f6b8240",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontSize":"12px",
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "size":{
                            "width":50,
                            "height":14}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"22126b12a53543c8a82d04191f4c9229",
                "label":"PM",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"67487fe3f1cb44aebdbb652362fe528c",
                    "label":"AM/PM",
                    "parentDynamicPanel":"c26b88e180ca4cf385fb5f6c3f6b8240",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "fontSize":"12px",
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "size":{
                        "width":50,
                        "height":14}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b46824fc23fb454e909febde5843f076",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"c26b88e180ca4cf385fb5f6c3f6b8240",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontSize":"12px",
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "size":{
                            "width":50,
                            "height":14}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"4baa3849a6934260a45030ac57567a6b",
            "label":"wifiTop",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":489,
                "y":162},
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onPanelStateChange":{
                "description":"OnPanelStateChange",
                "cases":[{
                    "description":"Case 1<br> (If &quot;[['0'.concat(hours).slice(-2)]]&quot; ≥ &quot;12&quot;)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":">=",
                      "leftExpr":{
                        "exprType":"stringLiteral",
                        "value":"[['0'.concat(hours).slice(-2)]]",
                        "localVariables":{
},
                        "stos":[{
                            "computedType":"string",
                            "sto":"fCall",
                            "thisSTO":{
                              "computedType":"string",
                              "desiredType":"string",
                              "sto":"fCall",
                              "thisSTO":{
                                "computedType":"string",
                                "desiredType":"string",
                                "sto":"literal",
                                "value":"0"},
                              "func":"concat",
                              "arguments":[{
                                  "sto":"var",
                                  "name":"hours"}]},
                            "func":"slice",
                            "arguments":[{
                                "computedType":"int",
                                "sto":"unOp",
                                "op":"-",
                                "inputSTO":{
                                  "computedType":"int",
                                  "sto":"literal",
                                  "value":2}}]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"12",
                        "stos":[]}},
                    "actions":[{
                        "action":"setPanelState",
                        "description":"设置 AM/PM to PM",
                        "panelsToStates":[{
                            "panelPath":["c26b88e180ca4cf385fb5f6c3f6b8240"],
                            "stateInfo":{
                              "setStateType":"diagram",
                              "stateNumber":2,
                              "stateValue":{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]},
                              "loop":false,
                              "showWhenSet":false,
                              "options":{
                                "compress":false}}}]},
{
                        "action":"setFunction",
                        "description":"设置 文字于 timeTop = &quot;[['0'.concat(hours).slice(-...&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetWidgetRichText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["ff218708f6f24d8e95f20e0c6e80781e"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"[['0'.concat(hours).slice(-2)-12]]:[['0'.concat(minutes).slice(-2)]]",
                                  "localVariables":{
},
                                  "stos":[{
                                      "computedType":"int",
                                      "sto":"binOp",
                                      "op":"-",
                                      "leftSTO":{
                                        "computedType":"string",
                                        "sto":"fCall",
                                        "thisSTO":{
                                          "computedType":"string",
                                          "desiredType":"string",
                                          "sto":"fCall",
                                          "thisSTO":{
                                            "computedType":"string",
                                            "desiredType":"string",
                                            "sto":"literal",
                                            "value":"0"},
                                          "func":"concat",
                                          "arguments":[{
                                              "sto":"var",
                                              "name":"hours"}]},
                                        "func":"slice",
                                        "arguments":[{
                                            "computedType":"int",
                                            "sto":"unOp",
                                            "op":"-",
                                            "inputSTO":{
                                              "computedType":"int",
                                              "sto":"literal",
                                              "value":2}}]},
                                      "rightSTO":{
                                        "computedType":"int",
                                        "sto":"literal",
                                        "value":12}},
{
                                      "computedType":"string",
                                      "sto":"fCall",
                                      "thisSTO":{
                                        "computedType":"string",
                                        "desiredType":"string",
                                        "sto":"fCall",
                                        "thisSTO":{
                                          "computedType":"string",
                                          "desiredType":"string",
                                          "sto":"literal",
                                          "value":"0"},
                                        "func":"concat",
                                        "arguments":[{
                                            "sto":"var",
                                            "name":"minutes"}]},
                                      "func":"slice",
                                      "arguments":[{
                                          "computedType":"int",
                                          "sto":"unOp",
                                          "op":"-",
                                          "inputSTO":{
                                            "computedType":"int",
                                            "sto":"literal",
                                            "value":2}}]}]},
{
                                  "exprType":"booleanLiteral",
                                  "value":true}]}]}}]},
{
                    "description":"Case 1<br> (If &quot;[['0'.concat(hours).slice(-2)]]&quot; &lt; &quot;12&quot;)",
                    "isNewIfGroup":true,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"<",
                      "leftExpr":{
                        "exprType":"stringLiteral",
                        "value":"[['0'.concat(hours).slice(-2)]]",
                        "localVariables":{
},
                        "stos":[{
                            "computedType":"string",
                            "sto":"fCall",
                            "thisSTO":{
                              "computedType":"string",
                              "desiredType":"string",
                              "sto":"fCall",
                              "thisSTO":{
                                "computedType":"string",
                                "desiredType":"string",
                                "sto":"literal",
                                "value":"0"},
                              "func":"concat",
                              "arguments":[{
                                  "sto":"var",
                                  "name":"hours"}]},
                            "func":"slice",
                            "arguments":[{
                                "computedType":"int",
                                "sto":"unOp",
                                "op":"-",
                                "inputSTO":{
                                  "computedType":"int",
                                  "sto":"literal",
                                  "value":2}}]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"12",
                        "stos":[]}},
                    "actions":[{
                        "action":"setPanelState",
                        "description":"设置 AM/PM to AM",
                        "panelsToStates":[{
                            "panelPath":["c26b88e180ca4cf385fb5f6c3f6b8240"],
                            "stateInfo":{
                              "setStateType":"diagram",
                              "stateNumber":1,
                              "stateValue":{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]},
                              "loop":false,
                              "showWhenSet":false,
                              "options":{
                                "compress":false}}}]},
{
                        "action":"setFunction",
                        "description":"设置 文字于 timeTop = &quot;[['0'.concat(hours).slice(-...&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetWidgetRichText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["ff218708f6f24d8e95f20e0c6e80781e"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"[['0'.concat(hours).slice(-2)]]:[['0'.concat(minutes).slice(-2)]]",
                                  "localVariables":{
},
                                  "stos":[{
                                      "computedType":"string",
                                      "sto":"fCall",
                                      "thisSTO":{
                                        "computedType":"string",
                                        "desiredType":"string",
                                        "sto":"fCall",
                                        "thisSTO":{
                                          "computedType":"string",
                                          "desiredType":"string",
                                          "sto":"literal",
                                          "value":"0"},
                                        "func":"concat",
                                        "arguments":[{
                                            "sto":"var",
                                            "name":"hours"}]},
                                      "func":"slice",
                                      "arguments":[{
                                          "computedType":"int",
                                          "sto":"unOp",
                                          "op":"-",
                                          "inputSTO":{
                                            "computedType":"int",
                                            "sto":"literal",
                                            "value":2}}]},
{
                                      "computedType":"string",
                                      "sto":"fCall",
                                      "thisSTO":{
                                        "computedType":"string",
                                        "desiredType":"string",
                                        "sto":"fCall",
                                        "thisSTO":{
                                          "computedType":"string",
                                          "desiredType":"string",
                                          "sto":"literal",
                                          "value":"0"},
                                        "func":"concat",
                                        "arguments":[{
                                            "sto":"var",
                                            "name":"minutes"}]},
                                      "func":"slice",
                                      "arguments":[{
                                          "computedType":"int",
                                          "sto":"unOp",
                                          "op":"-",
                                          "inputSTO":{
                                            "computedType":"int",
                                            "sto":"literal",
                                            "value":2}}]}]},
{
                                  "exprType":"booleanLiteral",
                                  "value":true}]}]}}]}]}},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"7f38822c784649fc9bd85debe881612a",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"004b39992fb54328ad875c6b54b6ca1b",
                    "label":"wifiTop",
                    "parentDynamicPanel":"4baa3849a6934260a45030ac57567a6b",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "size":{
                        "width":103,
                        "height":12}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"27312c965c904615845383308582fab2",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4baa3849a6934260a45030ac57567a6b",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "size":{
                            "width":103,
                            "height":12}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/wifitop_u17.png"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"df36a24f7b1a4c6088b0270d49475503",
                "label":"State2",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"232dcdcf24664cc2b73649b5bb21fbaa",
                    "label":"wifiTop",
                    "parentDynamicPanel":"4baa3849a6934260a45030ac57567a6b",
                    "panelIndex":1,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "size":{
                        "width":103,
                        "height":12}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a735d1a894f64403a67d4a06ef44e7e6",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4baa3849a6934260a45030ac57567a6b",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "size":{
                            "width":103,
                            "height":12}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/wifitop_u17.png"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"9e896ad8f7914635b6b1d62d4e329267",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":826,
                "y":162},
              "size":{
                "width":68,
                "height":11}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4d130b76d18942f6a32e589490683308",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":826,
                    "y":162},
                  "size":{
                    "width":68,
                    "height":11}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u21.png"}},
{
            "id":"f6fa6a363e0b41d09374e9445d326ea6",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":483,
                "y":841},
              "size":{
                "width":416,
                "height":50}},
            "adaptiveStyles":{
}},
{
            "id":"9cc3d7f379ba4641b0ddd30ab3240414",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFE45050,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "location":{
                "x":169.517517089844,
                "y":970.710632324219},
              "size":{
                "width":241,
                "height":28},
              "rotation":"345",
              "textRotation":"345"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da939a521e2549089dac12b8efb7cd7b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFE45050,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "location":{
                    "x":169.517517089844,
                    "y":970.710632324219},
                  "size":{
                    "width":241,
                    "height":28},
                  "rotation":"345",
                  "textRotation":"345"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u24.png"}},
{
            "id":"8ba38944d0c64cf68d9e4a737ed9c611",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":271.736206054688,
                "y":847.902587890625},
              "size":{
                "width":407,
                "height":356},
              "rotation":"30",
              "textRotation":"30",
              "cornerRadiusTopLeft":"36"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ea0ea430e15249cab353e5d185baca34",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":271.736206054688,
                    "y":847.902587890625},
                  "size":{
                    "width":407,
                    "height":356},
                  "rotation":"30",
                  "textRotation":"30",
                  "cornerRadiusTopLeft":"36"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u26.png"}},
{
            "id":"16c3db10afdf457ca8c5fc923b62b485",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":645,
                "y":901},
              "size":{
                "width":91,
                "height":79}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "7135079104fb499c812fb4a25818ee61":{
      "scriptId":"u0",
      "71e7261c93754d60bfca3c333757e5d4":{
        "scriptId":"u1"},
      "204649a0a9dc47eb89abd6a14d4dee21":{
        "scriptId":"u2"},
      "d700736c21484b85ad0944f69ac1e7c3":{
        "scriptId":"u3"},
      "cc0c88680ba74275bccb21c8d33ea1ba":{
        "scriptId":"u4"},
      "43b2f4d51be64871b568dfcaa3b2336b":{
        "scriptId":"u5"},
      "4646b51c0e674d0db291b14d326f31f8":{
        "scriptId":"u6"},
      "febbf591085046688dacfd42834355b7":{
        "scriptId":"u7"},
      "da4d2efdcb5140b0823431cbc21f605a":{
        "scriptId":"u8"},
      "4e9f28d7f8d24f1c8ac5423a22772cd8":{
        "scriptId":"u9"},
      "ff218708f6f24d8e95f20e0c6e80781e":{
        "scriptId":"u10"},
      "c26b88e180ca4cf385fb5f6c3f6b8240":{
        "scriptId":"u11"},
      "a0cc51770c704b1da4e8db2045b241ad":{
        "scriptId":"u12"},
      "9c4ef89875c2435db7b2e1110e920849":{
        "scriptId":"u13"},
      "67487fe3f1cb44aebdbb652362fe528c":{
        "scriptId":"u14"},
      "b46824fc23fb454e909febde5843f076":{
        "scriptId":"u15"},
      "4baa3849a6934260a45030ac57567a6b":{
        "scriptId":"u16"},
      "004b39992fb54328ad875c6b54b6ca1b":{
        "scriptId":"u17"},
      "27312c965c904615845383308582fab2":{
        "scriptId":"u18"},
      "232dcdcf24664cc2b73649b5bb21fbaa":{
        "scriptId":"u19"},
      "a735d1a894f64403a67d4a06ef44e7e6":{
        "scriptId":"u20"},
      "9e896ad8f7914635b6b1d62d4e329267":{
        "scriptId":"u21"},
      "4d130b76d18942f6a32e589490683308":{
        "scriptId":"u22"},
      "f6fa6a363e0b41d09374e9445d326ea6":{
        "scriptId":"u23"},
      "9cc3d7f379ba4641b0ddd30ab3240414":{
        "scriptId":"u24"},
      "da939a521e2549089dac12b8efb7cd7b":{
        "scriptId":"u25"},
      "8ba38944d0c64cf68d9e4a737ed9c611":{
        "scriptId":"u26"},
      "ea0ea430e15249cab353e5d185baca34":{
        "scriptId":"u27"},
      "16c3db10afdf457ca8c5fc923b62b485":{
        "scriptId":"u28"}},
    "a6fc58137f86469b907aa4df06ae0da6":{
      "scriptId":"u29"},
    "5085303de9a24c2888bec557297123db":{
      "scriptId":"u30"},
    "7e264161e7364a0c88a68ed3e7e12f6f":{
      "scriptId":"u31"},
    "318578aaa4da48918bc7d0f99960e971":{
      "scriptId":"u32"},
    "770e099b357e4d358fe7efb234dfb8c5":{
      "scriptId":"u33"},
    "86135c74df8341e0b33b7125fa7e32cb":{
      "scriptId":"u34"},
    "5a09cf7129f94a7cb771536aa2a39cf2":{
      "scriptId":"u35"},
    "2e94ada81e5a4f0a8c738c876123f1bd":{
      "scriptId":"u36"},
    "4177228e8e46435fab3890c8f7cb9653":{
      "scriptId":"u37"},
    "5a515c45a48d40dcb1460ee97fcef62e":{
      "scriptId":"u38"},
    "07d3b43575f64d3094ceb1b0f5410d03":{
      "scriptId":"u39"},
    "8424618f1b4e48e29dd87dba53228938":{
      "scriptId":"u40"},
    "617768a282de493b8f0b74fe599a9b31":{
      "scriptId":"u41"},
    "a203781d804f4273a8b1143a7fa127ed":{
      "scriptId":"u42"},
    "fcf3e1d3e4e34b6f972797dbb5615124":{
      "scriptId":"u43"},
    "2df206ed0b864b1a9ebbd33cbef26a35":{
      "scriptId":"u44"},
    "1a878da1c73c4e1c881430be15c2362c":{
      "scriptId":"u45"},
    "e701f125deb449c39ef9eef2ea3430d0":{
      "scriptId":"u46"},
    "34769ef1f5134dfe8c027f69c3975c77":{
      "scriptId":"u47"},
    "a21455b3b46c4c3294da67a98dddeb09":{
      "scriptId":"u48"}}});